module.exports = [
  {
    id: 'brig-001',
    name: 'Francicity Brigade',
    badge: 'FB',
    location: 'Francistown, Botswana',
    established: 1985,
    website: 'https://www.fb.ac.bw',
    about: 'Vocational training institution producing skilled artisans.',
  },
  {
    id: 'brig-002',
    name: 'Gaborone Brigade',
    badge: 'GB',
    location: 'Gaborone, Botswana',
    established: 1983,
    website: 'https://www.gb.ac.bw',
    about: 'Technical and vocational education centre.',
  },
  {
    id: 'brig-003',
    name: 'Palapye Brigade',
    badge: 'PB',
    location: 'Palapye, Botswana',
    established: 1988,
    website: 'https://www.pb.ac.bw',
    about: 'Hands-on vocational and technical training.',
  },
  {
    id: 'brig-004',
    name: 'Maun Brigade',
    badge: 'MB',
    location: 'Maun, Botswana',
    established: 1990,
    website: 'https://www.mb.ac.bw',
    about: 'Industry-focused technical education.',
  },
  {
    id: 'brig-005',
    name: 'Kanye Brigade',
    badge: 'KB',
    location: 'Kanye, Botswana',
    established: 1986,
    website: 'https://www.kb.ac.bw',
    about: 'Vocational training and artisan development.',
  },
  {
    id: 'brig-006',
    name: 'Serowe Brigade',
    badge: 'SB',
    location: 'Serowe, Botswana',
    established: 1987,
    website: 'https://www.sb.ac.bw',
    about: 'Skills training for technical careers.',
  },
  {
    id: 'brig-007',
    name: 'Molepolole Brigade',
    badge: 'MOB',
    location: 'Molepolole, Botswana',
    established: 1989,
    website: 'https://www.mob.ac.bw',
    about: 'Community-based technical education.',
  },
  {
    id: 'brig-008',
    name: 'Jwaneng Brigade',
    badge: 'JB',
    location: 'Jwaneng, Botswana',
    established: 1992,
    website: 'https://www.jb.ac.bw',
    about: 'Technical and vocational skills institution.',
  },
  {
    id: 'brig-009',
    name: 'Selibe Phikwe Brigade',
    badge: 'SPB',
    location: 'Selibe Phikwe, Botswana',
    established: 1984,
    website: 'https://www.spb.ac.bw',
    about: 'Practical artisan training centre.',
  },
  {
    id: 'brig-010',
    name: 'Tlokweng Brigade',
    badge: 'TB',
    location: 'Tlokweng, Botswana',
    established: 1991,
    website: 'https://www.tb.ac.bw',
    about: 'Technical education and vocational development.',
  },
];