module.exports = [
  {
    id: 'col-001',
    name: 'Gaborone Professional College',
    ownership: 'Public',
    badge: 'GPC',
    location: 'Gaborone, Botswana',
    established: 2003,
    website: 'https://www.gpc.ac.bw',
    about: 'Professional training institution focused on practical career development.',
  },
  {
    id: 'col-002',
    name: 'Francicity Business College',
    ownership: 'Private',
    badge: 'FBC',
    location: 'Francistown, Botswana',
    established: 2008,
    website: 'https://www.fbc.ac.bw',
    about: 'Business-focused college preparing students for modern workplaces.',
  },
  {
    id: 'col-003',
    name: 'Southern Skills College',
    ownership: 'Public',
    badge: 'SSC',
    location: 'Lobatse, Botswana',
    established: 2001,
    website: 'https://www.ssc.ac.bw',
    about: 'Skills-based training institution producing work-ready graduates.',
  },
  {
    id: 'col-004',
    name: 'Botswana Technology College',
    ownership: 'Private',
    badge: 'BTC',
    location: 'Gaborone, Botswana',
    established: 2010,
    website: 'https://www.btc.ac.bw',
    about: 'Specialised technology and ICT college.',
  },
  {
    id: 'col-005',
    name: 'Kalahari Professional Institute',
    ownership: 'Public',
    badge: 'KPI',
    location: 'Ghanzi, Botswana',
    established: 2006,
    website: 'https://www.kpi.ac.bw',
    about: 'Industry-driven vocational and academic programmes.',
  },
  {
    id: 'col-006',
    name: 'Northern Business College',
    ownership: 'Private',
    badge: 'NBC',
    location: 'Kasane, Botswana',
    established: 2012,
    website: 'https://www.nbc.ac.bw',
    about: 'Modern business and finance education.',
  },
  {
    id: 'col-007',
    name: 'Diamond Valley College',
    ownership: 'Public',
    badge: 'DVC',
    location: 'Jwaneng, Botswana',
    established: 2005,
    website: 'https://www.dvc.ac.bw',
    about: 'Career-oriented tertiary institution.',
  },
  {
    id: 'col-008',
    name: 'Okavango Career College',
    ownership: 'Private',
    badge: 'OCC',
    location: 'Maun, Botswana',
    established: 2014,
    website: 'https://www.occ.ac.bw',
    about: 'Focused on hospitality and tourism careers.',
  },
  {
    id: 'col-009',
    name: 'Pioneer Training College',
    ownership: 'Public',
    badge: 'PTC',
    location: 'Palapye, Botswana',
    established: 2004,
    website: 'https://www.ptc.ac.bw',
    about: 'Training institution delivering diploma programmes.',
  },
  {
    id: 'col-010',
    name: 'Thuto Professional College',
    ownership: 'Private',
    badge: 'TPC',
    location: 'Gaborone, Botswana',
    established: 2015,
    website: 'https://www.tpc.ac.bw',
    about: 'Modern college preparing graduates for the future workforce.',
  },
];